### ISSUE TITLE
Opens up the google registration form and the the program stops after filling it 

### ISSUE THREAD

**Issue by anuppoudel54** [temadol/gmail_generator#5]
Username:  ethicsrearrange124
Password: N1n3FTde7XSq12$

proxy:  190.112.193.59:1212
Traceback (most recent call last):
  File "C:\Users\anupp\Desktop\gmail_generator-master\WithOut_proxy_GmailBot.py", line 102, in <module>
    driver.find_element_by_xpath('//*[@class="RveJvd snByac"]').click()
  File "C:\Users\anupp\Desktop\gmail_generator-master\myenv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\anupp\Desktop\gmail_generator-master\myenv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\anupp\Desktop\gmail_generator-master\myenv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\anupp\Desktop\gmail_generator-master\myenv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //*[@class="RveJvd snByac"]

**Comment by davidmingueza98** [comment]
Yeah this is awful. The code is more than 1 year older and Google has actualized its webpage and the class names of the different elements. So if you want the script to work, you must rescrap the entire create account page and look for the good ids. Maybe it is better to put some more static identifier rather than a class name.

**Comment by anuppoudel54** [comment]
> Yeah this is awful. The code is more than 1 year older and Google has actualized its webpage and the class names of the different elements. So if you want the script to work, you must rescrap the entire create account page and look for the good ids. Maybe it is better to put some more static identifier rather than a class name.

Yeah figured out that much and proceeded to run it with success but shortly after account creation google said a bot made this so account was locked
